apiVersion: v1
kind: Namespace
metadata:
  name: bookinfo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    kiali.io/member-of: istio-system
    maistra.io/member-of: istio-system
spec: {}
