apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-elasticsearch
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: gitops/manifests/operators/openshift-elasticsearch-operator/base
    repoURL: https://github.com/samueltauil/servicemesh-bookinfo-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
