apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: openshift-workspaces
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  auth:
    identityProviderRealm: codeready
    updateAdminPassword: false
    identityProviderIngress: {}
    initialOpenShiftOAuthUser: true
    identityProviderContainerResources:
      limits: {}
      request: {}
    identityProviderClientId: codeready-public
    identityProviderPostgresSecret: che-identity-postgres-secret
    identityProviderRoute: {}
    externalIdentityProvider: false
    identityProviderSecret: che-identity-secret
    openShiftoAuth: true
  database:
    chePostgresContainerResources:
      limits: {}
      request: {}
    chePostgresDb: dbche
    chePostgresHostName: postgres
    chePostgresPort: '5432'
    externalDb: false
    postgresVersion: '13.3'
  devWorkspace:
    enable: false
  imagePuller:
    enable: false
    spec: {}
  k8s: {}
  metrics:
    enable: true
  server:
    cheLogLevel: INFO
    dashboardIngress: {}
    externalDevfileRegistry: false
    pluginRegistryIngress: {}
    cheServerRoute: {}
    devfileRegistryIngress: {}
    selfSignedCert: false
    cheServerIngress: {}
    cheDebug: 'false'
    tlsSupport: true
    dashboardRoute: {}
    allowUserDefinedWorkspaceNamespaces: false
    pluginRegistryRoute: {}
    devfileRegistryRoute: {}
    externalPluginRegistry: false
    workspaceNamespaceDefault: <username>-codeready
    serverExposureStrategy: multi-host
    gitSelfSignedCert: false
    useInternalClusterSVCNames: false
    cheFlavor: codeready
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    pvcStrategy: common
